### ISSUE TITLE
SCT codes for coronary artery calcium 

### ISSUE THREAD

**Issue by LennyN95** [MHubAI/SegDB#3]
We're looking to expand our SCT table with codes for delineation of **coronary artery calcium**.
We plan to report the calcification score under the code _450360000, Coronary artery calcification score (observable entity)_. However, if possible, it would be great to also allow the creation of a DicomSEG for plaque delineation but we have yet to find a suitable code for this.

We would like to involve the Dicom expert @dclunie in the discussion. If you have any suggestions for the right codes or pointers to the right direction, we would be very grateful :)

Are we looking for a disorder of the coronary arteries (e.g. 445512009) or for a morphologically abnormal structure (e.g. a code for calcium plaque) in the context of the coronary arteries?

Also, looping in @fedorov as the generated DicomSEG may be a potential candidate to be pushed back to [IDC](https://datacommons.cancer.gov/repository/imaging-data-commons) in the future.

**Comment by dclunie** [comment]
There is a template for describing plaque findings on CT, [TID 3911 Plaque Properties](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_TID_3911.html), and a corresponding value set [CID 3802 Plaque Structure](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_3802.html).

That uses the general concept [(18115005, SCT, "pathologic calcification")](http://snomed.info/id/18115005) in a context-specific manner. If you accompany your segment property code with an anatomic site of [(41801008, SCT, "Coronary artery")](http://snomed.info/id/41801008) or one of its branches (e.g., from [CID 3015 Coronary Artery](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_3015.html)).

PS. For the score, DICOM uses [TID 3905 Calcium Scoring Results](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_TID_3905.html) and specifically [(112058, DCM, "Calcium Score")](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_D.html#DCM_112058). That should probably be updated with [SCT:450360000](http://snomed.info/id/450360000).

**Comment by dclunie** [comment]
FYI - proposed DICOM CP to use SCT rather than DCM code for "Coronary artery calcification score":
[cp_dac636_01_calciumscore.pdf](https://github.com/MHubAI/SegDB/files/12857264/cp_dac636_01_calciumscore.pdf)

**Comment by LennyN95** [comment]
Thank you for your intense help @dclunie !
I updated our SegDB with the suggested codes and structures in 4110ec13532f16a4d8c27e3e2bc63556114a9bc1.

**Comment by LennyN95** [comment]
@fedorov fyi

**Comment by fedorov** [comment]
@dclunie what are the benefits of using those specialized templates, as opposed to TID 1500, in this particular case?

What we have for @LennyN95 dataset is the AI-derived score along with the segmentation of calcium and some anatomy.

If we use TID1500, we can rely on the already established infrastructure, and we would not lose any data to conversion. Introducing a new template, in my view, would need to bring significant benefits. Since this question is being asked in the context of contributing new data to IDC, I would want to see a convincing argument for using a new (relative to what is already supported) SR template to justify the additional effort to introduce and maintain new functionality in the IDC-supported ecosystem of tools.
