### ISSUE TITLE
Notation of Incomplete Structures

### ISSUE THREAD

**Issue by LennyN95** [MHubAI/SegDB#5]
Many segmentation models are restricted to a cropped field of view, often resulting in the delineation of incomplete structures (e.g., partial segmentation of the aorta in the axial direction).

@dclunie, @fedorov Is there any "marker" in SCT / DICOM to indicate the incompleteness (or describe the nature of the incompleteness)? If no, is this something we should think about or target (e.g. via comments or documentation)?

A simple "isComplete" flag might only lead to the question of "how complete" the structure is (or, inversely, what is missing).
However, thinking about the generation of large annotated datasets, it might be quite interesting to select (IDC query) samples where a complete segmentations for an ROI are available.

**Comment by dclunie** [comment]
This question sounds familiar and we may have discussed it in a QICR or IDC
context, but if so I cannot find it, nor does the standard have a specific
solution, nor can I find an existing CP about this.

If you want to signal that a particular Segment is incomplete (or complete), you
could theoretically include a modifier:

Segmented Property Type Modifier Code Sequence (0062,0011) =

     EV (255594003, SCT, "Complete")
or
     EV (255609007, SCT, "Partial")

Of you were sending an SR describing more detail about the segment (or defining
the segment as a contour rather than a bit plane) you could add a categorical
statement (Qualitative Evaluation) at the appropriate place in templates invoked
from TID 1500:

EV (255590007, SCT, "Extent") =

    EV (255594003, SCT, "Complete")
or
     EV (255609007, SCT, "Partial")

I suggested those codes because they have been used in another context in DICOM
already.

Alternatively:

EV (272143008, SCT, "Completeness") =

     EV (255594003, SCT, "Complete")
or
     EV (255599008, SCT, "Incomplete")

might be better, since both 255594003 and 255599008 are children of 272143008.

See "https://dailybuild.ihtsdotools.org/?perspective=full&conceptId1=272143008&edition=MAIN&release=&languages=en".

Alternatively, along the same lines:

EV (272142003, SCT, "Extensiveness") =

     EV (255503000, SCT, "Entire")
or
     EV (255609007, SCT, "Partial")

See "https://dailybuild.ihtsdotools.org/?perspective=full&conceptId1=272142003&edition=MAIN&release=&languages=en".

Note that (272142003, SCT, "Extensiveness") is a child (the only child) of (255590007, SCT, "Extent(s)"); see "https://dailybuild.ihtsdotools.org/?perspective=full&conceptId1=255590007&edition=MAIN&release=&languages=en".

I am some what "partial" to the entire/partial pattern since it seems closest to what
you are trying to describe.

David

**Comment by fedorov** [comment]
This is related to https://github.com/MHubAI/models/pull/39.

> Many segmentation models are restricted to a cropped field of view

What is the definition of "a cropped field of view"?

What if "a cropped field of view" happens to enclose the entire structure?

What if in your opinion it is complete, but in my opinion it is incomplete?

I think these modifiers should only be assigned if the model assigns them. Otherwise MHub would be taking on a role of potentially changing the semantics of the model output. If model developer says model segments heart, we should assign the code. If the model developer explicitly says it segments partial or entire heart - only then we should assign the modifiers discussed above.

**Comment by LennyN95** [comment]
> I think these modifiers should only be assigned if the model assigns them. Otherwise MHub would be taking on a role of potentially changing the semantics of the model output. If model developer says model segments heart, we should assign the code. If the model developer explicitly says it segments partial or entire heart - only then we should assign the modifiers discussed above.

That is (and will be) always the case. The Developer of the model/contributor will ultimatively decide. Our job is to give them the tools and options and to make it simple and sound. 

@dclunie Thank you for the (as always) super detailed response! It's good we have some options here. Using a modifier seems a good choice, however, what happens for structures already occupying a modifier  (e.g. Kidney with left modifier)?

**Comment by dclunie** [comment]
Use multiple modifiers if allowed (these are usually specified as 1-n)

On 12/18/23 10:04 AM, Leonard Nürnberg wrote:
...  
> @dclunie <https://github.com/dclunie> Thank you for the (as always) super detailed response! It's good we have some options here. Using a modifier seems a good choice, however, what happens for structures already occupying a modifier (e.g. Kidney with left modifier)?

**Comment by fedorov** [comment]
dcmqi does not support multiple modifiers at this time. As always, contributions to dcmqi are welcome. Also, inclusion of multiple modifiers will have consequences that are difficult to assess right away on the queries that interact with those objects in IDC. I would not spend time implementing this direction just because it is  potentially interesting until there is a real need and resources to provide implementation.

**Comment by LennyN95** [comment]
Agree, thx for the info. I want to keep the discussion on low prio though, so we know our options by the time it (might) become relevant. If we find a hour during the upcoming PW we can chat about options for dcmqi ;)
