### ISSUE TITLE
Add entry for `FDG-avid tumor`

### ISSUE THREAD

**Issue by LennyN95** [MHubAI/SegDB#7]
We were asked to add a code for FDG-avid tumor (NCIt C168968) by @vanossj: https://github.com/MHubAI/models/pull/79#issuecomment-2096182405

I couldn't find any equivalent in the SCT database; @fedorov, @dclunie, do you, by chance, know any suitable code in the SCT database we could use here? 

If no, any objections against adding the code as suggested by Jeff? NCIt is one of the coding scheme designators listed [here](https://dicom.nema.org/medical/dicom/current/output/html/part16.html#chapter_8).

**Comment by dclunie** [comment]
What are you going to use the code for and how? Is it the name of a name-value pair (and if so what are the values, yes/no?), or is it a single coded label for a region of interest that outlines a tumor that happens to be visible on an FDG PET scan (in which case is it better to just use a code for tumor, or a breast tumor in this case)? I ask because it is not clear to me from the [NCIt description ](https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C168968)which of the two this was intended for (or something else).

Not that there is any harm in saying FDG-avid tumor, but do you have Gd-avid tumor and iodinated contrast avid tumor too for MR and CT (or perhaps just enhancing tumor)? Just wondering how consistent the modeling of these concepts is.

There is no SCT equivalent of  FDG-avid tumor, AFAIK, and nothing mapped to any other coding scheme in UMLS either ([UMLS: C5239279](https://uts.nlm.nih.gov/uts/umls/concept/C5239279)).

If you are going to use the NCI Thesaurus code in a DICOM context, then yes, the correct coding scheme designator would be "[NCIt](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_8.html#para_d5493b38-f911-4441-9a8e-8a0fc9ea3f09)" (with the lowercase 't'), as you suggest.

**Comment by vanossj** [comment]
This is for follow up on two FDG PET models from last years AIMI project to add them mhub. We need to convert the metadata we used in those projects to mhub. In both cases its the label for semantic segmentation, there could be multiple fdg-avid tumors in the output.

* [Breast FDG PET/CT](https://github.com/bamf-health/aimi-breast-pet-ct/blob/main/app/src/dicom_seg_meta.json)
* [Lung FDG PET/CT](https://github.com/bamf-health/aimi-lung-pet-ct/blob/main/qa-results/dcm-meta/ai-dicom-seg-meta.json)

**Comment by fedorov** [comment]
@dclunie this topic and the decision to use this code    
      
```
          "CodeValue": "C168968",
          "CodingSchemeDesignator": "NCIt",
          "CodeMeaning": "FDG-Avid Tumor"
```

was documented here: https://docs.google.com/document/d/1BUhzwPIrCMRCEJUdPSJkp6kdA8_vlIP-miDPfpMrFZY/edit#heading=h.gsth6rnrdc4i.

**Comment by dclunie** [comment]
Thanks @fedorov, glad someone has a better memory than I do.

**Comment by LennyN95** [comment]
Thank you all for your input!

I added "FDG_AVID_TUMOR" using the suggested codes (4f506348f9fc3061eb0d4e334374dc071bbae4fb)
